# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NRT Tree Monitoring
email: sophia.just@geo.uni-marburg.de
description: >- # this means to ignore newlines until "baseurl:"
  PhytOakmeter, Near-Real-Time Monitoring, Proximity-Sensing, Imaging
baseurl: "" # the subpath of your site, e.g. /blog
url: https://SophiaJust.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SophiaJust

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# conversion
markdown: kramdown

include:
  - _pages
  - _data

collections_dir: sites

collections:
  europe:
    output: true
    permalink: /:collection/:title.html
  grassland:
    output: true
    permalink: /:collection/:title.html
  forest:
    output: true
    permalink: /:collection/:title.html
  CEE:
    output: true
    permalink: /:collection/:title.html

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # europe
  - scope:
      path: ""
      type: europe
    values:
      layout: single
      categories: transects europe
      sidebar:
        nav: "transects"
  # grassland
  - scope:
      path: ""
      type: grassland
    values:
      layout: single
      categories: transects grassland
      sidebar:
        nav: "transects"
  # forest
  - scope:
      path: ""
      type: forest
    values:
      layout: single
      categories: transects europe
      sidebar:
        nav: "transects"
  # CEE
  - scope:
      path: ""
      type: CEE
    values:
      layout: single
      categories: transects europe
      sidebar:
        nav: "CEE"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _posts
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
